### PR TITLE
Update Max10/Cyclone IV working cores status (Tested on De10_lite)

### PR DESCRIPTION
**Pull request by darfpga**
Tecmo : not enough RAM for De10_lite
QBert : Builds but cannot get menu

Test config : Scandoubler (VGA), NO Frame Buffer

### CODE REVIEW

**Comment by hansfbaier** [comment]
Many thanks for the testing! Great to see!

**Comment by yapinm** [comment]
@darfpga can you please share if you made any local changes before building cores for DE10Lite? Besides Menu core, all others marked as working are giving black(or white/grey) screen and no sound but F12 menu is working.
Roms matching md5sum in [db.json.zip](https://github.com/MiSTeX-devel/Distribution_MiSTeX/blob/2e423c761fcb1011b032e955f0bba670d5b5f006/db.json.zip) are placed in /media/fat/_Arcade/mame on rpi.
Am I missing something else to get it working?

**Comment by darfpga** [comment]
@yapinm, hello, yes I build core directly from depot. To be clear I build from quartus windows version so I need to adapt path in qsf file. You have to adapt openfpgaloader cmd and file extension in mister.ini. I also set scandoubler to active. One big difference may be that I compile main_mistex at commit fd68f9. Something goes wrong somewhere with more recent update. I don't know where.

To be absolutely clear I don't often load the core from rpi since I'am alway debugging. I load cores form quartus and trick fpgaloader cmd with 'ls' so that rpi continue to load roms. It requires also a fake <core name>.svf in cores folder. Let me know if it is ok for you.

**Comment by darfpga** [comment]
@yapinm, from commit 5bc5c7 you should either control button pin on rpi gpio or patch user_io.cpp around line 2759, change to : cur_btn = 0;

After commit abb798 there is also one more input pin IO_WIDE to wire from de10_lite board to rpi. de10lite_mistex.py have also to be updated.

**Comment by yapinm** [comment]
@darfpga Thank you for replies and pointers. I'll build it and test it on a weekend and let you know. Thanks again :)

**Comment by yapinm** [comment]
@darfpga I can confirm arcades are working with Main_Mistex at fd68f98d1f88e5409c10842a9cdf3abe2059546a with changes to Mister.ini:

--- MiSTer.ini  2024-04-26 19:15:14.098652115 +0200
+++ ../MiSTer.ini       1980-01-01 00:00:00.000000000 +0100
@@ -1,6 +1,6 @@
 [MiSTer]
 key_menu_as_rgui=0     ; set to 1 to make the MENU key map to RGUI in Minimig (e.g. for Right Amiga)
-forced_scandoubler=0   ; set to 1 to run scandoubler on VGA output always (depends on core).
+forced_scandoubler=1   ; set to 1 to run scandoubler on VGA output always (depends on core).
 ypbpr=0                ; set to 1 for YPbPr on VGA output.
 composite_sync=0       ; set to 1 for composite sync on HSync signal of VGA output.
 vga_scaler=1           ; set to 1 to connect VGA to scaler output.
@@ -213,4 +213,5 @@
 ; forced_scandoubler=0
 
 ; bitstream file extension (.rbf for Altera, .bit for Xilinx)
-bitstream_extension=.bit
+bitstream_extension=.svf
+fpgaloader_cmd=openFPGALoader -b de10lite


and then manually load core and mister on rpi(DE10Lite is connected to rpi via usb):
openFPGALoader -b de10lite /media/fat/_Arcade/cores/Arcade-[CORE_NAME]_nodsm.svf
/media/fat/MiSTer /media/fat/_Arcade/cores/Arcade-[CORE_NAME]_nodsm.svf /media/fat/_Arcade/[CORE's].mra

All cores built from latest commit (84013faa903313d741f46499ebdf9ede905bd877 ATM) on MiSTeX-ports.

Any advice for C64 core as it's the only one now with black screen?

**Pull request merged**
