### PR TITLE
initialise C64 core

### PR DESCRIPTION
**Pull request by darfpga**
Small config for initial debug :
- std kernel
- single drive
- no opl3

Currenlty start basic, load small cart (e.g. defender.crt) Kernel roms to be placed in build/<board>/C64/rtl/roms Required hps_interface to be fixed

### CODE REVIEW

**Comment by hansfbaier** [comment]
@darfpga upstream is https://github.com/MiSTer-devel/C64_MiSTer/, I suppose?

**Comment by hansfbaier** [comment]
Does it build and run successfully on your system?

**Comment by hansfbaier** [comment]
@darfpga What are the changes to hps_interface? I can't find them in the PR...
Or do you mean those of your past PR?
They already have been merged into master.

**Comment by hansfbaier** [comment]
Ok, after some modification to utils.py, mif files get copied automatically, 
and I can build the project.
Please still answer the question above.

**Comment by darfpga** [comment]
> @darfpga upstream is https://github.com/MiSTer-devel/C64_MiSTer/, I suppose?

Yes, right. My Git skill is not high enough to know how to add a submodule on remote repository.

**Comment by darfpga** [comment]
> @darfpga What are the changes to hps_interface? I can't find them in the PR... Or do you mean those of your past PR? They already have been merged into master.

I push them directly on cored/Template/sys on main branch.

**Comment by hansfbaier** [comment]
@darfpga I already made the necessary changes (except Template) and refactored a bit. Would you want to try if it still works for you?

**Comment by hansfbaier** [comment]
@darfpga I did not get a PR for Template. That means I would pull from your fork?

**Comment by hansfbaier** [comment]
@darfpga Ah, I already found it and pulled from your branch. Will update in ports.

**Comment by darfpga** [comment]
@hansfbaier Sorry for late reply. Everything is ok for me. At least same status as my own build. I have to adapt a bit sdram config (sdram is smaller on de10lite than MiSTer's one). I am going to try fixing 1541 loading, prg, crt, ... Don't know if problem is specific to my board or not.

**Comment by hansfbaier** [comment]
Ok, thanks for testing!

**Comment by darfpga** [comment]
> @darfpga I did not get a PR for Template. That means I would pull from your fork?

@hansfbaier Sorry I am not that comfortable with Git. Sometime I didn't do things correctly. More over i'am using GitDesktop on Windows, submodule management is not that clear for me. I run MiSTeX under WSL and 'switch' to Quartus on windows side for debug.

**Comment by hansfbaier** [comment]
No problem! Good to know it works with WSL!

**Pull request merged**
